name: generative_ai_flutter
description: "Sample app for the google_generative_ai package"

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_markdown: any
  # Note: best practice here is to use a caret version constraint. We use `any`
  # here just for the purpose of the sample.
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  another_flutter_splash_screen: ^1.2.1
  lottie: ^3.1.2
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Note: this section is only used in order to resolve google_generative_ai to
# the same repo as the sample.
dependency_overrides:
